"""
Shared base classes and mixins for all SQLAlchemy ORM entities.

- `UUIDMixin`: UUID primary key (`id`), generated by Postgres (gen_random_uuid)
  with a client-side uuid4 fallback for backends without that function.
- `TimestampMixin`: `created_at` / `updated_at` audit columns.
- `BaseEntity`: convenience base combining both mixins with `Base`.
- `TenantMixin`: optional `tenant_id` FK for tables that live in the shared
  `public` schema but still need to be scoped to a specific tenant (per
  ADR-002, most business tables are isolated via schema-per-tenant instead
  and do not need this mixin).
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, declared_attr, mapped_column
from sqlalchemy.sql import func

from app.config.database import Base


class UUIDMixin:
    """Adds a UUID primary key column named `id`."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        default=uuid.uuid4,
    )


class TimestampMixin:
    """Adds `created_at` / `updated_at` timestamp columns."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class BaseEntity(UUIDMixin, TimestampMixin, Base):
    """Abstract base class combining UUID PK and timestamp columns."""

    __abstract__ = True


class TenantMixin:
    """Adds a `tenant_id` FK column pointing at `public.tenants.id`.

    Intended for tables that live in the shared `public` schema but still
    need to be scoped to a specific tenant. Tables isolated via
    schema-per-tenant (the default strategy, see ADR-002) do not need this.
    """

    @declared_attr
    def tenant_id(cls) -> Mapped[uuid.UUID]:  # noqa: N805 - SQLAlchemy convention
        return mapped_column(
            UUID(as_uuid=True),
            ForeignKey("public.tenants.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )
